export const projects = [
        {
            "id": 1,
            "title": "English flashcards",
            "description": "I created an interactive flashcard app for English learners using React. Reusable components populate with JSON data on clickable cards that flip from one side to another. Cards are set and flipped with useState. The final project is deployed and hosted on Netlify.",
            "skills": "React, JavaScript, HTML, CSS",
            "thumbnail": "img/eng-mockup.png",
            "link": "https://englishcards.netlify.app/",
          },
          {
            "id": 2,
            "title": "Libertas Abogados",
            "description": "Libertas Abogados is a law firm in Bilbao, Spain which was looking to attract new clients. First, I analyzed the existing site and found it was very wordy, without clear contact info, with out of date email addresses. I sketched out my ideas on paper, then took those ideas to Sketch & InVision to create wireframes. Then I hand-coded the final project.",
            "skills": "UX Design, HTML, CSS, JavaScript, PHP",
            "thumbnail": "img/libertas.png",
            "link": "https://libertasabogados.net",
          },
          {
            "id": 3,
            "title": "Matthew Serna Therapy",
            "description": "Matthew Serna is a psychotherapist in the San Francisco Bay Area and was looking for a simple site to showcase his specialty areas and let clients easily schedule a consultation. The layout is a one-page resumé plus a scheduling and policy page. I chose to use WordPress for its strengths in SEO and smooth user experience, customizing some CSS elements.",
            "skills": "WordPress, JavaScript, Calendly",
            "thumbnail": "img/serna.png",
            "link": "https://matthewsernatherapy.com",
          },
          {
            "id": 4,
            "title": "Fertility calculators",
            "description": "As part of a small team, I followed design specifications to create a calculator to predict women's fertile days and possible pregnancy due dates. I used HTML, CSS and JavaScript/jQuery for the basic design. For the calendar, my colleague and I worked together to implement jQuery UI DatePicker and customized it with highly detailed CSS and jQuery. The calculator is live on Spanish website serpadres.es",
            "skills": "HTML, CSS, JavaScript, jQuery UI",
            "thumbnail": "img/fertility.png",
            "link": "https://www.serpadres.es/calculadora-fertilidad.html",
          },
          {
            "id": 5,
            "title": "Pharmaceutical articles",
            "description": "I researched and wrote articles related to pharmaceutical leadership and issues around the world for a digital publication with over 100,000 monthly visitors.",
            "skills": "Research, WordPress",
            "thumbnail": "img/pbr.png",
            "link": "https://pharmaboardroom.com/editor/?author_id=21609",
          },
          {
            "id": 6,
            "title": "Email marketing",
            "description": "Following design specifications from the company CEO, I customized HTML and CSS inside MailChimp to create attractive email campaigns for a global audience.",
            "skills": "HTML, CSS, MailChimp, UX Design",
            "thumbnail": "img/email.png", 
            "link": "https://dinaspencer.net/china-digest.html",
          },
    ]
