export const projects = [
  {
            "id": 1,
            "title": "Smart Energy AI",
            "description": "For my MBA final project with UNIR, I developed a product from ideation and strategy to hypothetical launch for GD Energy Services using SWOT, PESTEL and market analysis, positioning and segmentation strategy, financial and operational plans. The product is Smart Energy AI, an AI-based platform that monitors and reduces energy emissions in large industrial plants. The objective was to create a competitive advantage for GDES with a scalable, profitable and innovative solution.",
            "skills": "Strategy, analysis, communication, marketing, financial projection",
            "thumbnail": "img/mba-thumbnail.png",
            "link": "https://dinaspencer.net/pdf/GDES_PPT_DEFENSA.pdf",
          },
           {
            "id": 2,
            "title": "Autónomo Kit",
            "description": "After launching my blog about life in Spain and analyzing web traffic, I started to notice a demand for advice about becoming autónomo (self-employed) in Spain. Along with useful (and SEO-friendly) blog content, I created a free setup kit to help new self-employed teachers get set up, track clients and income, as well as funnel new contacts to my email list.",
            "skills": "SEO, blogging, web traffic, email marketing, content creation",
            "thumbnail": "img/digital-products.png",
            "link": "https://dinaspencer.net/autonomokit.html",
          },
        {
            "id": 3,
            "title": "English flashcards",
            "description": "I created an interactive flashcard app for English learners using React, with the objective of making speaking lessons more dynamic. Reusable components populate with JSON data on clickable cards that flip from one side to another. Cards are set and flipped with useState. The final project is deployed and hosted on Netlify.",
            "skills": "React, JavaScript, HTML, CSS",
            "thumbnail": "img/eng-mockup.png",
            "link": "https://englishcards.netlify.app/",
          },
          {
            "id": 4,
            "title": "Libertas Abogados",
            "description": "Libertas Abogados is a law firm in Bilbao, Spain which was looking to attract new clients. First, I analyzed the existing site and found it was very wordy, without clear contact info, with out of date email addresses. I sketched out my ideas on paper, then took those ideas to Sketch & InVision to create wireframes. Then I hand-coded the final project.",
            "skills": "Strategy, UX Design, HTML, CSS, JavaScript, PHP",
            "thumbnail": "img/libertas.png",
            "link": "https://libertasabogados.net",
          },
          {
            "id": 5,
            "title": "Matthew Serna Therapy",
            "description": "Matthew Serna is a psychotherapist in the San Francisco Bay Area and was looking for a simple site to showcase his specialty areas and let clients easily schedule a consultation. The layout is a one-page resumé plus a scheduling and policy page. I chose to use WordPress for its strengths in SEO and smooth user experience, customizing some CSS elements.",
            "skills": "WordPress, JavaScript, Calendly",
            "thumbnail": "img/serna.png",
            "link": "https://matthewsernatherapy.com",
          },
          // {
          //   "id": 6,
          //   "title": "Fertility calculators",
          //   "description": "As part of a small team, I followed design specifications to create a calculator to predict women's fertile days and possible pregnancy due dates. I used HTML, CSS and JavaScript/jQuery for the basic design. For the calendar, my colleague and I worked together to implement jQuery UI DatePicker and customized it with highly detailed CSS and jQuery. The calculator is live on Spanish website serpadres.es",
          //   "skills": "HTML, CSS, JavaScript, jQuery UI",
          //   "thumbnail": "img/fertility.png",
          //   "link": "https://www.serpadres.es/calculadora-fertilidad.html",
          // },
          {
            "id": 7,
            "title": "Pharmaceutical articles",
            "description": "I researched and wrote articles related to pharmaceutical leadership and issues around the world for a digital publication with over 100,000 monthly visitors.",
            "skills": "Research, WordPress",
            "thumbnail": "img/pbr.png",
            "link": "https://pharmaboardroom.com/editor/?author_id=21609",
          },
          {
            "id": 8,
            "title": "Email marketing",
            "description": "Following design specifications from the company CEO, I customized HTML and CSS inside MailChimp to create attractive email campaigns for a global audience.",
            "skills": "HTML, CSS, MailChimp, UX Design",
            "thumbnail": "img/email.png", 
            "link": "https://dinaspencer.net/china-digest.html",
          },
    ]
